[2024-08-04T23:11:46.802+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-04T23:11:46.831+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_api_data.transfer_to_dw scheduled__2024-08-04T23:00:00+00:00 [queued]>
[2024-08-04T23:11:46.837+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_api_data.transfer_to_dw scheduled__2024-08-04T23:00:00+00:00 [queued]>
[2024-08-04T23:11:46.838+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-08-04T23:11:46.848+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transfer_to_dw> on 2024-08-04 23:00:00+00:00
[2024-08-04T23:11:46.858+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'ingest_api_data', 'transfer_to_dw', 'scheduled__2024-08-04T23:00:00+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/ingest_api_data.py', '--cfg-path', '/tmp/tmpd54dkd9g']
[2024-08-04T23:11:46.860+0000] {standard_task_runner.py:91} INFO - Job 109: Subtask transfer_to_dw
[2024-08-04T23:11:46.861+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=450) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-08-04T23:11:46.861+0000] {standard_task_runner.py:64} INFO - Started process 452 to run task
[2024-08-04T23:11:46.898+0000] {task_command.py:426} INFO - Running <TaskInstance: ingest_api_data.transfer_to_dw scheduled__2024-08-04T23:00:00+00:00 [running]> on host 52830206e1a2
[2024-08-04T23:11:46.972+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='MS_sIX2Rm@somosyoung.com.br' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_api_data' AIRFLOW_CTX_TASK_ID='transfer_to_dw' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-04T23:00:00+00:00'
[2024-08-04T23:11:46.974+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-04T23:11:46.986+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-08-04T23:11:46.997+0000] {base.py:84} INFO - Using connection ID 'postgres_dw' for task execution.
[2024-08-04T23:11:50.938+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2024-08-04T23:11:50.941+0000] {process_utils.py:132} INFO - Sending 15 to group 452. PIDs of all processes in the group: [452]
[2024-08-04T23:11:50.943+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 452
[2024-08-04T23:11:50.944+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-08-04T23:11:51.160+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-04T23:11:51.169+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ingest_api_data.py", line 151, in transfer_to_dw
    rows = src_cursor.fetchall()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/_json.py", line 162, in typecast_json
    return loads(s)
           ^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 343, in raw_decode
    def raw_decode(self, s, idx=0):
    
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-08-04T23:11:51.176+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_api_data, task_id=transfer_to_dw, run_id=scheduled__2024-08-04T23:00:00+00:00, execution_date=20240804T230000, start_date=20240804T231146, end_date=20240804T231151
[2024-08-04T23:11:51.238+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=452, status='terminated', exitcode=2, started='23:11:46') (452) terminated with exit code 2
[2024-08-04T23:11:51.239+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 143
[2024-08-04T23:11:51.255+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-04T23:11:51.775+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
